name: Tests
on:
  push:
    branches:
      - '**' # Ignore all tags, otherwise tests will run twice on release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fix .npmrc for CI/CD
        run: |
            echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGE_TOKEN }}" >> ~/.npmrc
      - name: Install modules and test
        run: |
          yarn
          yarn test
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
